version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: "postgres:latest"
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"

  producer:
    build: ./transaction-producer-ms
    depends_on:
      - rabbitmq
    volumes:
      - ./hackathon-asapcard/INPUT:/app/input

  consumer:
    build: ./transaction-consumer-ms
    depends_on:
      - rabbitmq
      - postgres
